postsubmits:
  - name: post-banka-3-infrastructure-helm-build
    always_run: true
    decorate: true
    max_concurrency: 1
    labels:
      preset-harbor-robot-push: "true"
    spec:
      containers:
        - image: harbor.k8s.elab.rs/base-images/base:java-17-node-18-docker
          command:
            - /bin/bash
            - -c
            - |
              set -euo pipefail

              TEAM_NAME="banka-3"

              helm registry login -u $HARBOR_USERNAME -p $HARBOR_PASSWORD harbor.k8s.elab.rs

              helm lint backend
              helm lint frontend

              helm package backend
              helm package frontend

              file=$(find . -maxdepth 1 -type f -name "${TEAM_NAME}-backend-*.tgz" -printf "%f\n")
              helm push "$file" oci://harbor.k8s.elab.rs/banka-3/helm

              file=$(find . -maxdepth 1 -type f -name "${TEAM_NAME}-frontend-*.tgz" -printf "%f\n")
              helm push "$file" oci://harbor.k8s.elab.rs/banka-3/helm

          securityContext:
            privileged: true
          imagePullPolicy: Always