apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ .Release.Name }}-bank-service
  name: {{ .Release.Name }}-bank-service
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-bank-service
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-bank-service
    spec:
      containers:
      - image: harbor.k8s.elab.rs/banka-3/bank-service:{{ .Values.imageTag }}
        imagePullPolicy: Always
        name: bank-service
        env:
        - name: SPRING_DATASOURCE_URL
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-db-pguser-bank-db
              key: jdbc-uri
        - name: SPRING_DATASOURCE_USERNAME
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-db-pguser-bank-db
              key: user
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-db-pguser-bank-db
              key: password
        - name: SPRING_JPA_HIBERNATE_DDL_AUTO
          value: create-drop
        - name: SPRING_RABBITMQ_HOST
          value: banka-3-rabbitmq
        - name: SPRING_RABBITMQ_PORT
          value: "5672"
        - name: SPRING_RABBITMQ_USERNAME
          value: user
        - name: SPRING_RABBITMQ_PASSWORD
          valueFrom:
            secretKeyRef:
              name: banka-3-rabbitmq
              key: rabbitmq-password
        - name: SPRING_CLOUD_OPENFEIGN_CLIENT_CONFIG_USER-SERVICE_URL
          value: http://{{ .Release.Name }}-user-service:8080
        - name: SPRING_CLOUD_OPENFEIGN_CLIENT_CONFIG_STOCK-SERVICE_URL
          value: http://{{ .Release.Name }}-stock-service:8083
        - name: SPRING_CLOUD_OPENFEIGN_CLIENT_CONFIG_BANK2_API_URL
          value: https://banka-2.si.raf.edu.rs/api/user-service

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Release.Name }}-bank-service
  name: {{ .Release.Name }}-bank-service
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - port: 8082
    protocol: TCP
    targetPort: 8082
  selector:
    app: {{ .Release.Name }}-bank-service
  type: ClusterIP